In [16]:
import torch

In [17]:
input_img = torch.randn((1,10))

In [18]:
input_img

tensor([[-0.4592,  1.6775, -0.9098, -0.2049,  1.3921,  1.1010, -0.6235,  0.7711,
          1.0895,  0.6371]])

In [19]:
weights = torch.randn_like(input_img)

In [20]:
weights

tensor([[-1.1841, -0.5216,  0.1011, -1.1512, -0.7289, -0.1930, -1.3286,  1.6897,
         -1.4760,  0.3786]])

In [21]:
bias = torch.randn((1,1))

In [22]:
bias

tensor([[-0.0018]])

In [29]:
output = torch.mm(input_img, weights.view(10, 1)) + bias

In [30]:
output

tensor([[-0.6522]])

In [25]:
def sigmoid(x):
    return 1/(1+torch.exp(-x))

In [26]:
output = sigmoid(output)

In [27]:
output

tensor([[0.3425]])