In [1]:
import torch

In [4]:
x = torch.Tensor([1,2,3])

In [5]:
x

tensor([1., 2., 3.])

In [7]:
x[2]

tensor(3.)

In [8]:
x.shape

torch.Size([3])

In [9]:
x + torch.Tensor([4,4,4])

tensor([5., 6., 7.])

In [10]:
x + 5

tensor([6., 7., 8.])

In [11]:
x = torch.Tensor([[1,2,3], [4,5,6]])

In [12]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [13]:
x[0,1]

tensor(2.)

In [14]:
x + 5

tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [15]:
x = torch.randn((1,5))

In [16]:
x

tensor([[-0.0925, -1.1851, -0.9960, -1.7479, -0.5656]])

In [17]:
x = torch.randn((2,3))

In [18]:
x

tensor([[-0.4634,  1.5057, -0.9811],
        [ 1.1651, -0.0303,  1.3819]])