In [2]:
import torch

In [3]:
input_img = torch.randn((1,10))

In [5]:
input_img

tensor([[-1.7421, -0.8900, -0.6507,  1.5800, -1.2034, -0.5692,  0.7412, -0.2664,
          0.3991, -0.4792]])

In [4]:
weights = torch.randn_like(input_img)

In [6]:
weights

tensor([[ 0.8777, -0.9809, -1.1042,  0.8711,  2.3276, -0.1578, -0.0451, -0.9701,
          0.6272, -1.2583]])

In [7]:
bias = torch.randn((1,1))

In [8]:
bias

tensor([[-1.2265]])

In [14]:
output = torch.sum(input_img * weights) + bias

In [15]:
output

tensor([[-1.4205]])

In [16]:
def sigmoid(x):
    return 1/(1+torch.exp(-x))

In [18]:
output = sigmoid(output)

In [19]:
output

tensor([[0.1946]])