In [1]:
import torch

In [4]:
x = torch.randn((1,5), requires_grad=True)

In [5]:
x

tensor([[ 0.7498, -0.8380, -0.5907,  0.0789,  0.9881]], requires_grad=True)

In [6]:
b = x + 2

In [8]:
b

tensor([[2.7498, 1.1620, 1.4093, 2.0789, 2.9881]], grad_fn=<AddBackward0>)

In [9]:
c = b * 2

In [10]:
c

tensor([[5.4995, 2.3240, 2.8185, 4.1578, 5.9762]], grad_fn=<MulBackward0>)

In [11]:
c = c.mean()

In [12]:
c

tensor(4.1552, grad_fn=<MeanBackward0>)

In [13]:
x.grad

In [14]:
c.backward()

In [15]:
x.grad

tensor([[0.4000, 0.4000, 0.4000, 0.4000, 0.4000]])